### ISSUE TITLE
AllTasksFinished fires multiple times

### ISSUE THREAD

**Issue by lainz** [wadman/wthread#3]
Hi, I've added a lot of tasks (5) on this project (Open Source if you want to check)
https://github.com/Arandusoft/fpcpaymowidget

I start all tasks like this:
```
DownloadCompany.Start;
DownloadProjects.Start;
DownloadTasks.Start;
DownloadTaskLists.Start;
DownloadRunningTimer.Start;
```
And the method fires multiple times.

**Comment by wadman** [comment]
Hi, Thanks u! I corrected this bug. Wait for then next commit...

**Comment by lainz** [comment]
Thank you for this excelent tool =)
