### ISSUE TITLE
Can't close app correctly

### ISSUE THREAD

**Issue by lainz** [wadman/wthread#4]
Hi, I'm using your component on this project (Open Source if you want to check)
https://github.com/Arandusoft/fpcpaymowidget

I can't close the app correctly.

The bug is always in the last line I start a task.

Any ideas?

**Comment by wadman** [comment]
Hi!
I can not reproduce the error. I do not have enough package fpcpaymowidtgetscontrols.

**Comment by wadman** [comment]
Make sure that you check the flag Sender.Terminated at the time of the task execution.

**Comment by lainz** [comment]
Hi, the package is inside the folder controls.

How I can check that?

**Comment by wadman** [comment]
The task is performed until the Sender.Terminated is set. Sender.WaitMs also checks this flag. The thread does not interrupt the task. The task itself must be completed correctly.

procedure TForm1.Task3Execute(const Sender: TTask; const Msg: Word; var Param: Variant);
var i: integer;
begin
    i := 10;
    while (i > 0) and (not Sender.Terminated) do begin
        dec(i);
        Sender.WaitMs(1000);
    end;
end;

**Comment by lainz** [comment]
Ok, thanks I will add that flag and see what happens.

**Comment by lainz** [comment]
Hi, is the same, it points an error always on the last task started.
![error_on_task](https://user-images.githubusercontent.com/4131395/38138985-e14b0a0c-3403-11e8-9406-9dce9d1ef6ce.PNG)

**Comment by wadman** [comment]
This flag needs to be checked during the execution of a long operation. If the flag is checked after a long operation, it does not help to interrupt the operation correctly.

**Comment by lainz** [comment]
Is only called on create, it then finishes before the form is shown.
At the moment of application close there is no task running.

```
procedure TfrmMain.DownloadRunningTimerExecute(const Sender: TTask;
  const Msg: word; var Param: variant);
begin
  if not Sender.Terminated then
    Paymo.GetRunningTimer();
end;
```

Operations does not take too much, are just api downloads, so 1 second or 2 max. But I use your component because I can download all of them in parallel.

**Comment by wadman** [comment]
I strongly ask you to apply a clean draft, where your error is reproduced only on the source code of the lazarus. Unfortunately, I do not have much free time to debug full-fledged applications with third-party libraries.
Try your application without additional thread (without TWCThread). If the memory leaks, the problem is in other libraries.
Thank you for understanding! :)

**Comment by wadman** [comment]
You can write to me on self@wadman.ru the test login on the server and in the presence of free time I will try to tell what the problem may be.
On my experience, handlers json and xml often lead to memory leaks.

**Comment by lainz** [comment]
Sure, I understand, I'm also working, and also I develop open source libraries.

I will do for all bugs I reported test in small apps, and then will report it here. Please don't close this two bugs, I will report back, if is my fault (sure it is), I will close them.

Maybe because all threads access the same object, and that can cause problems.

**Comment by wadman** [comment]
OK!  I will wait for your messages.

**Comment by lainz** [comment]
Hi again. Here is something strange. When I'm not using Lazarus and I run the application from the .exe, it starts and finish normally, with no error. The memory leak window shows 0 exceptions and 0 leak.

It can be that the threads are loaded also when Lazarus is running? I mean: in the form editor?

Or maybe the debugger?

**Comment by wadman** [comment]
Hi. Debugger can make mistakes, since it is not really friendly with debugging threads.

**Comment by wadman** [comment]
Try to remove the work with the thread. Delete the component, and perform the tasks as follows:
```
procedure TfrmMain.FormCreate(Sender: TObject);
var r: variant;
begin
  r := 0;
  //DoubleBuffered := True;
  pnlMenu.Left := 0;
  pnlMenu.Top := 0;
  Paymo := TPaymo.Create;
  Paymo.LoadSettings;
  Login;
  if Paymo.LoggedIn then
  begin
    try
      //DownloadCompany.Start;
      //DownloadProjects.Start;
      //DownloadTasks.Start;
      //DownloadTaskLists.Start;
      //DownloadRunningTimer.Start;
      DownloadCompanyExecute(nil, 1, r);
      DownloadProjectsExecute(nil, 1, r);
      DownloadTasksExecute(nil, 1, r);
      DownloadTaskListsExecute(nil, 1, r);
      DownloadRunningTimerExecute(nil, 1, r);
    except
    end;
  end;
end;        
```
```
procedure TfrmMain.FormDestroy(Sender: TObject);
begin
  //wcThreadDownloader.FinishAllTasks();
  if Assigned(Paymo) then
    Paymo.Free;
end;
```
You will remove errors related to the work of the thread.

**Comment by lainz** [comment]
Hi, I think is the debugger. I can start and stop at any time the application without the debugger and works fine.

I get no exceptions and no memory leaks outside the debugger / lazarus.

Thanks for your time, I will make this: add an ifdef that uses threads and other with no threads, so I can debug memory leaks, but also get the benefits of threaded application. Your code snippet will help me on doing this. Is double effort but until debugger get's fixed is a workaround.
