### ISSUE TITLE
How to start a finished task again?

### ISSUE THREAD

**Issue by lainz** [wadman/wthread#5]
Hi, I need to run a task again, because it grabs data from internet that must be updated. Is possible to reuse a task to do this?

When I start the task again, it does not run again.

**Comment by wadman** [comment]
Task1.Start should correctly run the task at any time (**if at that time other tasks are not running**). All tasks are performed in the order of the queue.
You need to make a test application, where each action will be logged into the TMemo, in order to understand how this mechanism works.
A minimal example of an application is applied to the package.

**Comment by lainz** [comment]
Ok. So if I do

`Task1.Start`

and then it finish, then I can do again

`Task1.Start`

But for any reason the second call does not works. And all tasks are finished at that time.

**Comment by wadman** [comment]
Can you show a minimal project where this error is reproduced?

In this project, you can press the button any number of times and the task will be executed correctly.

```
unit Unit1;

{$mode objfpc}{$H+}

interface

uses
    Classes, SysUtils, FileUtil, Forms, Controls, Graphics, Dialogs, StdCtrls, wcthread;

type

    { TForm1 }

    TForm1 = class(TForm)
        Button1: TButton;
        Memo1: TMemo;
        Task1: TTask;
        WCThread1: TWCThread;
        procedure Button1Click(Sender: TObject);
        procedure Task1Execute(const Sender: TTask; const Msg: Word; var Param: Variant);
        procedure Task1Finish(const Sender: TTask; const Msg: Word; const Param: Variant);
    private

    public

    end;

var
    Form1: TForm1;

implementation

{$R *.lfm}

{ TForm1 }

procedure TForm1.Button1Click(Sender: TObject);
begin
    Task1.Start;
end;

procedure TForm1.Task1Execute(const Sender: TTask; const Msg: Word; var Param: Variant);
begin
    Sender.WaitMs(1000);
end;

procedure TForm1.Task1Finish(const Sender: TTask; const Msg: Word; const Param: Variant);
begin
    Memo1.Lines.Add('Task finished');
end;

end.
```

**Comment by lainz** [comment]
Ok, in the application FPCPaymoWidget in this exact revision:
https://github.com/Arandusoft/fpcpaymowidget/commit/ab3f238010b09b489be6395dedbf287d6d385896

You need to have a running task (in this revision, you need to create the task in the website and then run the application)

```
procedure TfrmMain.lblStopClick(Sender: TObject);
begin
  if (Paymo.RunningTimerData <> nil) then
  begin
    case Paymo.StopRunningTimer(start_time, now, '') of
      prOK: begin
        pnlTime.Visible := False;
        DownloadRunningTimer.Start;
      end;
      prTRYAGAIN, prERROR: begin
        ShowMessage(rsErrorCantStopTimer);
      end;
    end;
  end;
end;
```

The task was called before OnCreate event

```
procedure TfrmMain.FormCreate(Sender: TObject);
begin
  DoubleBuffered := True;
  pnlMenu.Left := 0;
  pnlMenu.Top := 0;
  Paymo := TPaymo.Create;
  Paymo.LoadSettings;
  Login;
  if Paymo.LoggedIn then
  begin
    try
      DownloadCompany.Start;
      DownloadProjects.Start;
      DownloadTasks.Start;
      DownloadRunningTimer.Start;
      DownloadTaskLists.Start;
    except
    end;
  end;
end;
```

But I will try to create a small app to see if I'm doing something wrong.

**Comment by lainz** [comment]
Hi, it's working, but I get a memory leak. Attached project.

And also the same problem of "Can't close" the application.
[project1.zip](https://github.com/wadman/wthread/files/1864842/project1.zip)

Run with the build mode 'Debug'. Run it and close it several times to get the error.

If memleak window is not shown, is also an error.

![threaderror](https://user-images.githubusercontent.com/4131395/38154837-b2d4d6b6-344a-11e8-86b6-61533e4c2583.PNG)

I'm using Lazarus trunk, FPC trunk.

**Comment by wadman** [comment]
Hi! You made a big error by referring to the visual part from another thread. 
You can not change the contents of TMemo. Only by sending a message from the thread and processing it in the OnMessage event.
Example: 
```
unit Unit1;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, Forms, Controls, Graphics, Dialogs, StdCtrls, wcthread;

type

  { TForm1 }

  TForm1 = class(TForm)
    Memo1: TMemo;
    Task1: TTask;
    Task2: TTask;
    WCThread1: TWCThread;
    procedure FormCreate(Sender: TObject);
    procedure Task1Execute(const Sender: TTask; const Msg: Word;
      var Param: Variant);
    procedure Task1Message(const Sender: TTask; const Msg: Word; const Param: Variant);
    procedure Task2Execute(const Sender: TTask; const Msg: Word;
      var Param: Variant);
    procedure Task2Message(const Sender: TTask; const Msg: Word; const Param: Variant);
  private

  public

  end;

var
  Form1: TForm1;

implementation

{$R *.lfm}

{ TForm1 }

procedure TForm1.Task1Execute(const Sender: TTask; const Msg: Word;
  var Param: Variant);
begin
  Sender.PostMessage(1, 'executed task 1');
end;

procedure TForm1.Task1Message(const Sender: TTask; const Msg: Word; const Param: Variant);
begin
    case Msg of
        1: Memo1.Lines.Add(Param);
    end;
end;

procedure TForm1.FormCreate(Sender: TObject);
begin
  Task1.Start;
  Task2.Start;
  Task1.Start;
end;

procedure TForm1.Task2Execute(const Sender: TTask; const Msg: Word;
  var Param: Variant);
begin
    Sender.PostMessage(1, 'executed task 2');
end;

procedure TForm1.Task2Message(const Sender: TTask; const Msg: Word; const Param: Variant);
begin
    case Msg of
        1: Memo1.Lines.Add(Param);
    end;
end;

end.
```

**Comment by lainz** [comment]
Ok, thanks for the help. Now I see that there must be bugs in my code, I was not aware of how threads should be used.

But is not a bug, I can directly run a finished task, so there must be something else in my code.
