### ISSUE TITLE
HELP please: correct way to break a task

### ISSUE THREAD

**Issue by Lurgainn** [wadman/wthread#6]
Hi,
thank you very much for your package. I want to use it for a little project that I'm creating.
I have a utility developed with Lazarus that show a form with a progress bar and receive command from stdin. This utility is launched from a LUA script that get the handle of its stdin and send commands to that handle.
The section that receive the command is a task create with your component, and the routine send the commands to the main task (the GUI) with the PostMessage method.
In the task there's a continuous loop that only check the Sender.Terminated.
The significant section of the program is this:

```
procedure TformMain.TaskStdinExecute(const Sender: TTask; const Msg: Word;
							var Param: Variant);

var
    keyEvent: TKeyEvent;
    stdin: String = '';

begin
    keyboard.InitKeyboard;
    while not Sender.Terminated do
    begin
        keyEvent := PollKeyEvent;
    	if keyEvent <> 0 then
	    begin
			keyEvent := GetKeyEvent;
	        keyEvent := TranslateKeyEvent(keyEvent);
	        if GetKeyEventFlags(keyEvent) = kbASCII then
	        begin
	            if ((Ord(GetKeyEventChar(keyEvent)) = 10) or
	            	(Ord(GetKeyEventChar(keyEvent)) = 13)) then
	            begin
	                Sender.PostMessage(WM_MY_MESSAGE, stdin);
	                stdin := '';
	            end
	            else
	            begin
	            	stdin := stdin + KeyEventToString(keyEvent);
	            end
	        end
		end;
    end;
    keyboard.DoneKeyboard;
end;

procedure TformMain.TaskStdinFinish(const Sender: TTask; const Msg: Word;
						const Param: Variant);

begin
	ShowMessage('This thread terminated');
end;

procedure TformMain.TaskStdinMessage(const Sender: TTask; const Msg: Word;
						const Param: Variant);

var
    my_inp: String;
    my_value: LongInt;

begin
    ShowMessage(Param);
	if Msg = WM_MY_MESSAGE then
    begin
        my_inp := LowerCase(Param);
        if my_inp = 's' then
        begin
            formMain.Show;
        end
        else if my_inp = 'h' then
        begin
            formMain.Hide;
		end
		else if my_inp = 'q' then
        begin
        	formMain.Close;
		end;
	end;
end;

procedure TformMain.threadStdinAllTasksFinished(const Sender: TWCthread);

begin
    ShowMessage('All threads terminated');
end;

end.
```

**My problem is:**

When the TaskStdinMessage receive the string 'q', the program must end, but the task TaskStdinExecute that read the stdin is running, so **which is the correct way to terminate the task and only after that quit the program?**
Actually, in my program the methods 'TaskStdinFinish' and 'threadStdinAllTasksFinished' never show.

Forgive me for the length of my post and thank very much for any help that you'll give me.

**Comment by Lurgainn** [comment]
Further analysis showed that the first problem is related to keyboard management in the Execute procedure of the task.
It seems that keystroke polling/handling interferes with message dispatch between tasks, but I can't understand why.
However, while I will be doing other tests, it would be useful to have the answer at least to the second point, that is, while the Execute procedure of the task is still running (the execution is a closed loop that controls only Sender.Terminate), **what is the correct way for the primary process of the GUI to interrupt and cancel the task releasing all the resources?**
Thanks again

**Comment by wadman** [comment]
Hi, Lurgainn!

You cannot access the keyboard and GUI directly from the thread. To do this, use the message queue. Your task does not need an additional thread. All this should run in the main thread.

PS. OnFinish will be executed when the task completes normally. Terminated is the abnormal completion of a task or application.

Sample:
`
unit Unit1;

{$mode objfpc}{$H+}

interface

uses
    Classes, SysUtils, Forms, Controls, Graphics, Dialogs, StdCtrls, wcthread;

const
    WM_SET_LABEL = 1;

type

    { TForm1 }

    TForm1 = class(TForm)
        Button1: TButton;
        Button2: TButton;
        Label1: TLabel;
        SimpleTask: TTask;
        WCThread1: TWCThread;
        procedure Button1Click(Sender: TObject);
        procedure Button2Click(Sender: TObject);
        procedure FormCreate(Sender: TObject);
        procedure SimpleTaskExecute(const Sender: TTask; const Msg: Word; var Param: Variant);
        procedure SimpleTaskFinish(const Sender: TTask; const Msg: Word; const Param: Variant);
        procedure SimpleTaskMessage(const Sender: TTask; const Msg: Word; const Param: Variant);
    private
        FTaskFinished: boolean;
    public

    end;

var
    Form1: TForm1;

implementation

{$R *.lfm}

{ TForm1 }

procedure TForm1.FormCreate(Sender: TObject);
begin
    FTaskFinished := false;
    SimpleTask.Start;
end;

procedure TForm1.Button1Click(Sender: TObject);
begin
    SimpleTask.Stop; // terminate task, not finish
end;

procedure TForm1.Button2Click(Sender: TObject);
begin
    FTaskFinished := true; //
end;

procedure TForm1.SimpleTaskExecute(const Sender: TTask; const Msg: Word; var Param: Variant);
var i: integer;
begin
    i := 0;
    while not Sender.Terminated do begin
        Sender.WaitMs(100); // hard work emulation
        if FTaskFinished then break; // normal completion of the task, OnFinish will be executed
        inc(i, 1);
        Sender.PostMessage(WM_SET_LABEL, IntToStr(i)); // send message to main thread
    end;
end;

procedure TForm1.SimpleTaskFinish(const Sender: TTask; const Msg: Word; const Param: Variant);
begin
    ShowMessage('Finished!'); // task normally finished, not terminated
end;

procedure TForm1.SimpleTaskMessage(const Sender: TTask; const Msg: Word; const Param: Variant);
begin
    case Msg of
        WM_SET_LABEL: Label1.Caption := Param; // this event will be executed in main thread
    end;
end;

end.
`

**Comment by Lurgainn** [comment]
Thanks very much. Now I understand and I'll close this issue.
And thanks again for your work.
Bye.
