### ISSUE TITLE
Linux 32 bit

### ISSUE THREAD

**Issue by lainz** [wadman/wthread#7]
Hi, we're using this component for a cross platform application. In a form we're using it to query some data from internet to display a QR code. It works on Linux 64 but I'm having issues on Linux 32. The QR is never displayed.

Can you confirm wthread works correctly on Linux 32? I'm using Ubuntu 16.04

**Comment by lainz** [comment]
Apparently what is not triggered is the OnFinish event of the TTask. But I'm not sure if it's just in my project or not.

**Comment by lainz** [comment]
Tested one of your test project, and OnFinish is executed, so the fault is our code...

**Comment by wadman** [comment]
Hi!
Please show your code.

**Comment by lainz** [comment]
Hi, I solved the problem using normal threads, too much time trying to find the problem. But your component works, only our code was not adapted to it and we can't find any other solution than switching to normal threads.

**Comment by wadman** [comment]
Hi!

I would like to fix the problem if it exists in my code. Or I could help solve it.

**Comment by lainz** [comment]
Hi ok. Is just on Linux 32 so you need to use a VM or a machine with it.
If I'm right the problem was starting a TTask from OnFinish event.

But again, the demos provided works on Linux 32 so the problem was that I described or something else.

**Comment by wadman** [comment]
Is this example enough to reproduce the problem?

unit Unit1;

{$mode objfpc}{$H+}

interface

uses
    Classes, SysUtils, Forms, Controls, Graphics, Dialogs, wcthread;

type

    { TForm2 }

    TForm2 = class(TForm)
        Task1: TTask;
        Task2: TTask;
        WCThread1: TWCThread;
        procedure FormCreate(Sender: TObject);
        procedure Task1Execute(const Sender: TTask; const Msg: Word; var Param: Variant);
        procedure Task1Finish(const Sender: TTask; const Msg: Word; const Param: Variant);
        procedure Task2Execute(const Sender: TTask; const Msg: Word; var Param: Variant);
        procedure Task2Finish(const Sender: TTask; const Msg: Word; const Param: Variant);
    private

    public

    end;

var
    Form2: TForm2;

implementation

{$R *.lfm}

{ TForm2 }

procedure TForm2.FormCreate(Sender: TObject);
begin
    Task1.Start;
    Caption := 'Task1 Started';
end;

procedure TForm2.Task1Execute(const Sender: TTask; const Msg: Word; var Param: Variant);
begin
    Sender.WaitMs(1000);
end;

procedure TForm2.Task1Finish(const Sender: TTask; const Msg: Word; const Param: Variant);
begin
    Task2.Start;
    Caption := 'Task1 Finished, Task2 Started';
end;

procedure TForm2.Task2Execute(const Sender: TTask; const Msg: Word; var Param: Variant);
begin
    Sender.WaitMs(1000);
end;

procedure TForm2.Task2Finish(const Sender: TTask; const Msg: Word; const Param: Variant);
begin
    Caption := 'Task2 Finished';
end;

end.

**Comment by lainz** [comment]
That also works.

**Comment by lainz** [comment]
I'm sorry that  I can't provide a demo that fails
The problem is that it requires a full application that is private and I can't share 
Is something that happens with bugs these only appear on certain conditions

**Comment by wadman** [comment]
Understand. I'm sorry we didn’t solve the problem.
