### ISSUE TITLE
Need example

### ISSUE THREAD

**Issue by TonyStone31** [wadman/wthread#8]
Can you give me an example how I would create X number of tasks at runtime?

I would like to let my user choose number of tasks with a spin edit with a max set by numofThreadsTouse.MaxValue:=thrdGenerate.ProcessorCount;

I dropped a thread component on form.  I created 1 task with my code in it.  Is there a way I could basically make that exact task with code during run time?

for i:= 0 to numOfThreadsToUse
task1.create[i]

etc...
Or is there some functionality already in your component that I am missing?

And I want to say ahead of time I am sorry if this is very basic.  My skills are very basic at this point.

**Comment by TonyStone31** [comment]
This is what I have so far... but I seem to get an error about listindex out of bounds.

     for i:= 0 to sedtThreads.Value do
     begin
        WCThread.Tasks.Count:=i;
         WCThread.Task[i].Create(WCThread);
         wcthread.Task[i].OnExecute:=@onexecut;
         WCThread.Task[i].Start;

     end;

**Comment by wadman** [comment]
Hi!
You need to create threads (TWCThread), not tasks (TTask). Assign a processor mask to each thread. The task in this case is like a message for the thread indicating what task the thread will run at the current moment. 

Fully working example with emulated work:


```
unit mainForm;

{$mode objfpc}{$H+}

interface

uses
    Classes, SysUtils, Forms, Controls, Graphics, Dialogs, StdCtrls, wsqltypes, wcthread;

const
    MSG_LOG = 1;

type

    { TForm1 }

    TForm1 = class(TForm)
        Button1: TButton;
        Memo1: TMemo;
        Task1: TTask;
        WCThread1: TWCThread;
        procedure Button1Click(Sender: TObject);
        procedure Task1Execute(const Sender: TTask; const Msg: Word; var Param: Variant);
        procedure Task1Message(const Sender: TTask; const Msg: Word; const Param: Variant);
    private

    public

    end;

var
    Form1: TForm1;

implementation

{$R *.lfm}

{ TForm1 }

procedure TForm1.Task1Execute(const Sender: TTask; const Msg: Word; var Param: Variant);
var log: string;
    i: integer;
begin
    // emulation of work in an additional thread
    for i := 0 to 10000 do begin
        If Sender.Terminated then exit; // check terminated
        Sender.WaitMs(1000); // wait 1 sec
        log := Format('%s counter is %d', [Sender.Owner.Name, i]);
        Sender.PostMessage(MSG_LOG, log); // sending a message to the main thread
    end;
end;

procedure TForm1.Task1Message(const Sender: TTask; const Msg: Word; const Param: Variant);
var log: string;
begin
    // its the main thread
    case Msg of
        MSG_LOG: begin
            // message from thread/task
            log := Param;
            Memo1.Lines.Add(FormatDateTime('hh:nn:ss.zzz ', Now)+log);
        end;
    end;
end;

procedure TForm1.Button1Click(Sender: TObject);
var i: integer;
    thread: TWCThread;
    task: TTask;
begin
    // create threads
    Memo1.Lines.Clear;
    for i := 0 to WCThread1.ProcessorCount-1 do begin
        thread := TWCThread.Create(Self);
        thread.Name := Format('Thread%d', [i]);
        thread.AffinityMask := i+1;
        Memo1.Lines.Add(Format('%s AffinityMask is %d', [thread.Name, thread.AffinityMask])); // checking the use of the mask
        task := TTask.Create(thread);
        task.Name := Format('Task%d', [i]);
        task.OnExecute := @Task1Execute;
        task.OnMessage := @Task1Message;
        task.Start; // executing a task on a specified thread
    end;
end;

end.


```

**Comment by TonyStone31** [comment]
Well... I feel really stupid now. lol

When I get a chance I am going to try and implement your code into my project.  Thanks for this example!  It will certainly get me started.  And I am quite new to this so if I come back with more stupid questions please excuse me.

**Comment by TonyStone31** [comment]
so I get this error:
 raised exception class 'External: SIGSEGV'.

 In file 'wcthread.pas' at line 328:
result := FTerminated;

I am not understanding why...

**Comment by TonyStone31** [comment]
ahhaa!  So the wthread package from the Online Package Manager was old.  I removed that from my Lazarus install and installed from this github page and the issue has resolved itself!  Thank you very much for your component by the way!  I love the design of it.  Threading should be as easy as your component is aiming to make it!  I can try and continue my project now... again... I will probably be back!

**Comment by TonyStone31** [comment]
ok... so now my issue is how do i properly reference these created threads at run time when it is time to stop them and destroy them?  here is what I have got so far in my start button.... 

`procedure TfrmMain.btnStartStopClick(Sender: TObject);
var
  i: integer;
  arthread:  TWCThread;
  artask:  TTask;
begin
    if btnStartStop.Caption = 'Start' then
    begin
       tkStart:=GetTickCount64;
       lstBulk.Lines.Clear;
      for i := 0 to sedtThreads.Value-1 do begin
          arthread := TWCThread.Create(Self);
          arthread.Name := Format('Thread%d', [i]);
          arthread.AffinityMask := i+1;

          artask := TTask.Create(arthread);
          artask.Name := Format('Task%d', [i]);

          artask.OnExecute := @Task1Execute;
          artask.OnMessage := @Task1Message;
          artask.Start;
      end;
      btnStartStop.Caption:='Stop';
      sedtThreads.Enabled:=False;
      exit;
    end;

      // this stopping doesnt work
      // i tried declaring a global var of
      // artask: array of ttask
      // arthread: array of TWCThread
      // now I am back to this code that wont stop tasks....
      // i feel like i know the issue but dont know how to address it
    if btnStartStop.Caption = 'Stop' then
    begin
      for i := 0 to sedtThreads.Value-1 do begin
        artask[i].Stop;
        Sleep(200);
        if arthread[i].Task[i].IsFinished then
        arthread[i].Destroy;
      end;
     btnStartStop.Caption:='Start';
    end;

end;    `

**Comment by TonyStone31** [comment]
ok... so now my issue is how do i properly reference these created threads at run time when it is time to stop them and destroy them? here is what I have got so far in my start button....

procedure TfrmMain.btnStartStopClick(Sender: TObject);
var
  i: integer;
  arthread:  TWCThread;
  artask:  TTask;
begin
    if btnStartStop.Caption = 'Start' then
    begin
       tkStart:=GetTickCount64;
       lstBulk.Lines.Clear;
      for i := 0 to sedtThreads.Value-1 do begin
          arthread := TWCThread.Create(Self);
          arthread.Name := Format('Thread%d', [i]);
          arthread.AffinityMask := i+1;

          artask := TTask.Create(arthread);
          artask.Name := Format('Task%d', [i]);

          artask.OnExecute := @Task1Execute;
          artask.OnMessage := @Task1Message;
          artask.Start;
      end;
      btnStartStop.Caption:='Stop';
      sedtThreads.Enabled:=False;
      exit;
    end;

      // this stopping doesnt work
      // i tried declaring a global var of
      // artask: array of ttask
      // arthread: array of TWCThread
      // now I am back to this code that wont stop tasks....
      // i feel like i know the issue but dont know how to address it
    if btnStartStop.Caption = 'Stop' then
    begin
      for i := 0 to sedtThreads.Value-1 do begin
        artask[i].Stop;
        Sleep(200);
        if arthread[i].Task[i].IsFinished then
        arthread[i].Destroy;
      end;
     btnStartStop.Caption:='Start';
    end;

end;

**Comment by wadman** [comment]
Threads are bound to the form (TWCThread.Create(Self)) and will be automatically destroyed along with it. Threads can be created in the "FormCreate" method and forgot about them. Then work only with tasks. Tasks can be obtained in the "Task" flow method. 
In your code, the created threads and their tasks are not saved anywhere (in array or list). The code is strange. You should start with the basics of Pascal. 

```
unit Unit1;

{$mode objfpc}{$H+}

interface

uses
    Classes, SysUtils, Forms, Controls, Graphics, Dialogs, StdCtrls, wcthread;

const
    WM_MSG = 1;

type

    { TForm1 }

    TForm1 = class(TForm)
        butStart: TButton;
        butStop: TButton;
        Memo1: TMemo;
        Task1: TTask;
        WCThread1: TWCThread;
        procedure butStartClick(Sender: TObject);
        procedure butStopClick(Sender: TObject);
        procedure FormCreate(Sender: TObject);
        procedure Task1Execute(const Sender: TTask; const Msg: Word; var Param: Variant);
        procedure Task1Message(const Sender: TTask; const Msg: Word; const Param: Variant);
    private
        FThreads: array of TWCThread;
    public

    end;

var
    Form1: TForm1;

implementation

{$R *.lfm}

{ TForm1 }

procedure TForm1.FormCreate(Sender: TObject);
var i: integer;
    task: TTask;
begin
    SetLength(FThreads, TWCThread.ProcessorCount);
    for i := Low(FThreads) to High(FThreads) do begin
        FThreads[i] := TWCThread.Create(Self);
        FThreads[i].AffinityMask := i+1;
        task := TTask.Create(FThreads[i]);
        task.Name := Format('Task%d', [i]);
        task.OnExecute := @Task1Execute;
        task.OnMessage := @Task1Message;
    end;
end;

procedure TForm1.butStartClick(Sender: TObject);
var i: integer;
begin
    for i := Low(FThreads) to High(FThreads) do begin
        FThreads[i].Task[0].Start;
        Sleep(50);
    end;
end;

procedure TForm1.butStopClick(Sender: TObject);
var i: integer;
begin
    for i := Low(FThreads) to High(FThreads) do begin
        FThreads[i].Task[0].Stop;
        Sleep(50);
    end;
end;

procedure TForm1.Task1Execute(const Sender: TTask; const Msg: Word; var Param: Variant);
begin
    Sender.PostMessage(WM_MSG, Format('%s %s', [Sender.Name, 'Im started']));
    while not Sender.Terminated do begin
        Sender.WaitMs(1000);
        Sender.PostMessage(WM_MSG, Format('%s %s', [Sender.Name, 'Im alive!']));
    end;
end;

procedure TForm1.Task1Message(const Sender: TTask; const Msg: Word; const Param: Variant);
begin
    case Msg of
        WM_MSG: Memo1.Lines.Add(Param);
    end;
end;

end.

```

**Comment by TonyStone31** [comment]
I guess my problem with trying to create an array of twcthread was that using the first code example you gave me I was not able to stop the tasks in the threads.  When tried to access the created threads from the Button1Click procedure I couldn't... or at least didnt know how to.  So when I created the threads and declared them as an array in the button I still couldn't access the .task.  

So the problem I was having is hard to describe since it is 24 hours later and I tried a million different things.  But I just put the         FThreads: array of TWCThread; in the private declarration of the form and now when i type fthreads[i]. the tasks do show up.  

Anyway... I am going to play with some things and basically implement what you are showing me in your last example.  I do appreciate your help.  I am slowly learning the basics of Pascal... this is how.  I did find a book I was considering ordering... For now I am trying to learn by example.

**Comment by TonyStone31** [comment]
Thanks for your examples and assistance.  For the most part I have a nice working application.  I want to let you know the version of your threading components in the Online Package Manager of Lazarus seems to be a bit different than what you have on GitHub.  Your examples had all kinds of issues using the older verion in the package manager.  When I installed it from the GitHub package it resolved my issues!  Thank you for your work on this component!
