### ISSUE TITLE
Lazarus v2.2.0RC1 Issue?

### ISSUE THREAD

**Issue by TonyStone31** [wadman/wthread#9]
I just did a fresh install of the latest Lazarus release candidate v2.2.0RC1.  I open my project which is using your compnent and I am getting compile errors now.  Can you look into these errors when you are free?

wcthreadreg.pas(156,69) Error: Incompatible type for arg no. 1: Got "untyped", expected "<procedure variable type of procedure(TPersistent) of object;Register>"
wcthreadreg.pas(194,49) Error: Illegal expression
wcthreadreg.pas(198,49) Error: Illegal expression
wcthreadreg.pas(225,72) Error: Incompatible type for arg no. 1: Got "untyped", expected "<procedure variable type of procedure(TPersistent) of object;Register>"
wcthreadreg.pas(321,54) Error: Illegal expression

**Comment by wadman** [comment]
Support a RC is a costly operation. Parameters of procedures may differ between different RCs. 
I have already encountered this behavior, so I'm waiting for the full release.

**Comment by TonyStone31** [comment]
I would like to send you a tip(small payment) for your component.  It has been very useful to me!  And you have helped me out already.  Do you take any crypto currency payments by chance?  Or use PayPal?  Or any other projects where i can send a donation for your time?

**Comment by wadman** [comment]
Oh... Please, check it. I haven't updated lazarus, just looked at its sources. 

[wthread_laz2_2.zip](https://github.com/wadman/wthread/files/6860432/wthread_laz2_2.zip)

**Comment by TonyStone31** [comment]
So it seems to compile and work awesome as usual now!  Thank you.  I do want you to know however there is still an access violation error that happens when I click the ... in the Tasks item of the object inspector.  The only way I can edit tasks is by right clicking on the component on the form and selecting Edit Tasks from there.  That has been a bug since I started using it, so it seems.  Also when I use it on a form and I delete the component from my form, it causes errors in Lazarus.

I get this error a few seconds after deleting the component from the form:
An exception occurred during deletion of
"WCThread1:TWCThread"
Access violation

Then at this point I need to open the forms lfm file and remove it manually...

I am creating the component at run-time currently so this is not a big issue but I wanted you to know.

I am running on Linux Mint if that matters.

**Comment by wadman** [comment]
Hi! Check it please
[wthread_laz2_2_a.zip](https://github.com/wadman/wthread/files/6944122/wthread_laz2_2_a.zip)

**Comment by TonyStone31** [comment]
I still get
An exception occurred during deletion of
"WCThread1:TWCThread"
Access violation

when removing the component from my form.

And I still get an Access Violation error when trying to edit tasks from the Object inspector.

**Comment by wadman** [comment]
Hi! You can check the latest version from the repository.
